devices:
  - label: TEST-DEV-1
    host: 1.2.3.4
    username: ADMIN
    password: PASSWORD-HERE
    enabled: true
  - label: TEST-DEV-2
    host: 4.3.2.1
    username: ADMIN
    password: PASSWORD-HERE
    enabled: false